My_project/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('myShop.urls')),


]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myShop/urls.py
from . import views
from django.urls import include, re_path
app_name = 'myShop'
urlpatterns = [
    re_path(r'^home$', views.home, name='home'),
    re_path(r'^product/(?P<id>\w+)/$', views.product, name='product'),
    re_path(r'^basket/$', views.basket, name='basket'),
    re_path(r'^checkout/$', views.checkout , name='checkout'),
    re_path(r'^pdf/$', views.generate_pdf , name='generate_pdf'),
]

myShop/models.py
from django.db import models
from django.db.models.signals import post_save


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class MeasuredUnit(models.Model):
    measured_unit_id = models.IntegerField(primary_key=True)
    name = models.TextField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'measured_unit'


class ProductCategory(models.Model):
    category_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)

    class Meta:
        managed = True
        db_table = 'product_category'
        verbose_name_plural = 'product_category'

    def __str__(self):
        return self.name


class Status(models.Model):
    status_id = models.AutoField(primary_key=True)
    status_name = models.CharField(max_length=24, null=False, default=None)
    is_active = models.BooleanField(default=True)

    class Meta:
        managed = True
        db_table = 'Status'
        verbose_name_plural = 'Status'

    def __str__(self):
        return self.status_name


class Customers(models.Model):
    customer_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.CharField(max_length=30, null=True, unique=True)
    address = models.CharField(max_length=20, null=True, default=None)
    phone = models.CharField(max_length=13, null=True, default=None, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'customers'
        verbose_name_plural = 'customers'


class Orders(models.Model):
    customer = models.ForeignKey(Customers, on_delete=models.CASCADE, default=None)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    order_id = models.AutoField(primary_key=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE, default=None)
    payment_type = models.CharField(max_length=25, default='Cash')
    order_timestamp = models.DateTimeField(auto_now_add=True, blank=True)
    delivery_type = models.CharField(max_length=50)

    def __str__(self):
        return str(self.order_id)

    class Meta:
        managed = True
        db_table = 'orders'
        verbose_name_plural = 'orders'

class Brand(models.Model):
    brand_name = models.CharField(max_length=40)

    def __str__(self):
        return str(self.brand_name)

    class Meta:
        managed = True
        db_table = 'brand'

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    size = models.IntegerField()
    amount = models.IntegerField()
    product_info = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=18, decimal_places=2)
    product_name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)  #is_saled
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, default=None)
    measured_unit = models.ForeignKey(MeasuredUnit, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return str(self.product_name)
    class Meta:
        managed = True
        db_table = 'product'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=None)
    product_image = models.ImageField(upload_to='images/')
    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'product_image'

    def __str__(self):
        return str(self.id)


class ProductInOrder(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE, default=None)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=None)
    count = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)


    def __str__(self):
        return self.product.product_name

    class Meta:
        managed = True
        db_table = 'ProductInOrder'

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        total_price = price_per_item * int(self.count)
        self.total_price = total_price

        return super(ProductInOrder, self).save(*args, **kwargs)


class Basket(models.Model):
    session_key = models.CharField(max_length=128,blank=True, null=True, default=None)
    order = models.ForeignKey(Orders, on_delete=models.CASCADE, null=True, default=None)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=None)
    count = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_shown = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.product.product_name

    class Meta:
        managed = True
        db_table = 'Basket'

    def save(self, is_shown=None, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        total_price = price_per_item * int(self.count)
        self.total_price = total_price
        if is_shown is not None:
            self.is_shown=False
        return super(Basket, self).save(*args, **kwargs)


def product_in_order_post_save(instance, **kwargs):
    order = instance.order
    all_products_in_order = ProductInOrder.objects.filter(order=order)
    order_total_price = 0
    for item in all_products_in_order:
        order_total_price += item.total_price
    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)


post_save.connect(product_in_order_post_save, sender=ProductInOrder)

myShop/forms.py
import re

from django import forms
from .models import *

class CustomersForm(forms.ModelForm):
    class Meta:
        model = Customers
        exclude=['customer_id']

class CheckoutBuyerForm(forms.Form):
    delivery_list = [('Відділення "Нова почта"', 'Відділення "Нова почта"'), ("Кур`єр", "Кур`єр")]
    payment_list = [('Готівка', 'Готівка'), ('Кредитна карта', 'Кредитна карта')]

    name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    address = forms.CharField(required=True)
    email = forms.CharField(required=True)
    payment_type = forms.ChoiceField(choices=payment_list, required=True)
    delivery_type = forms.ChoiceField(choices=delivery_list, required=True)
    delivery_list = [('Відділення "Нова почта"', 'Відділення "Нова почта"'), ("Кур`єр", "Кур`єр")]
    payment_list = [('Готівка', 'Готівка'), ('Кредитна карта', 'Кредитна карта')]

    class Meta:
        model = Customers
        exclude=['customer_id']


class ProductFilterForm(forms.Form):
    category = ProductCategory.objects.all()
    brands = Brand.objects.all()
    list_categories = [('', 'Всі категорії')]
    list_brands = [('', 'Всі бренди')]
    for i in brands:
        list_brands.append((i.id, i.brand_name))

    for i in category:
        list_categories.append((i.category_id, i.name))

    list_size = [('','Всі розміри')]
    for i in range(30,45,1):
        list_size.append((i,i))

    product_name = forms.CharField(required=False, label='Назва товару')
    min_price = forms.DecimalField(required=False, label='Мінімальна ціна')
    max_price = forms.DecimalField(required=False, label='Максимальна ціна')
    brand = forms.ChoiceField(choices=list_brands, label='Бренд', widget=forms.RadioSelect, required=False)
    category = forms.ChoiceField(choices=list_categories, label='Категорія', widget=forms.RadioSelect, required=False, )
    size = forms.ChoiceField(choices=list_size, label='Розміри', required=False, )

myShop/templates/myShop/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        {% if  is_any_product == True  %}
            <div class="col-lg-12">
                <h1 class="product_name">
                    <div class="text-center">
                        Товари в корзині
                    </div>
                </h1>
                <form class="form-horizontal" method="post">{% csrf_token %}
                    <table class="table text-center">
                    <thead>
                        <tr>
                            <th>Товар</th>
                            <th>Кількість</th>
                            <th>Ціна за одиницю</th>
                            <th>Загальна ціна за товар</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product_basket in products_in_basket %}
                            <tr>
                                <td>
                                    {{ product_basket.product.product_name }}
                                </td>
                                <td>
                                    <input value="{{ product_basket.count }}" type="number" min="1"
                                           class="product-in-basket-amount" name="number_in_basket_{{ product_basket.id }}">
                                </td>
                                <td>
                                    <span class="product-in-basket-price">
                                        {{ product_basket.price_per_item }} грн
                                    </span>
                                </td>
                                <td>
                                    <span class="total_product_in_basket_amount">
                                        {{ product_basket.total_price }} грн
                                    </span>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <div class="text-right">
                    <b>Сума замовлення:</b> <span id="total_order_amount">{{ price_for_order }} грн</span>

                </div>

                <div class="text-right">
                    <button type="submit" onClick="refreshPage()" class="btn btn-primary btn-lg">Замовити</button>
                </div>
                <div class="text-left">
                    {% if form.errors %}
                    <div class="alert alert-danger" style="display: inline-block;">
                            Помилка при обробці даних
                    </div>
                {% endif %}
                </div>
                {% include 'myShop/form_order.html' %}
            </form>
            </div>
        {% else %}
            <h1 class="no_product_basket">
                <div class="text-center">
                    Немає товарів в корзині
                </div>
            </h1>
            </div>
            {% if pdf %}
                <div class="text-center">
                        <a href="{% url 'myShop:generate_pdf' %}" class="btn btn-primary">Створити pdf файл покупки</a>
                {% endif %}
                </div>
        {% endif %}

    </div>
</div>
{% endblock %}

myShop/templates/myShop/form_order.html
 <div class="col-lg-2">
     <div class="form-group">
         <label>Ім'я</label>
         <span class="form-error">{{ form.name.errors }}</span>
         <input type="text" name="{{ form.name.html_name }}" class="custom-input" autocomplete="off">
     </div>
     <div class="form-group">
         <label>Прізвищe</label>
         <span class="form-error">{{ form.last_name.errors }}</span>
         <input type="text" name="{{ form.last_name.html_name }}" class="custom-input" autocomplete="off">
     </div>
     <div class="form-group">
         <label>Телефон</label>
         <span class="form-error">{{ form.phone.errors }}</span>
         <input type="text" name="{{ form.phone.html_name }}" class="custom-input" autocomplete="off">
     </div>
     <div class="form-group">
         <label>Почта</label>
         <span class="form-error">{{ form.email.errors }}</span>
         <input type="text" name="{{ form.email.html_name }}" class="custom-input" autocomplete="off">
     </div>
     <div class="form-group">
         <label>Адреса</label>
         <span class="form-error">{{ form.address.errors }}</span>
         <input type="text" name="{{ form.address.html_name }}" class="custom-input" autocomplete="off"></div>

     <div class="form-group">
         <label>Тип оплати</label>
            <span class="form-error">{{ form.payment_type.errors }}</span>
            <select name="{{ form.payment_type.html_name }}" class="custom-input">
                <option value="" selected disabled>Виберіть тип оплати</option>
                {% for value, label in payment_choices %}
                    <option value="{{ value }}">{{ label }}</option>
                {% endfor %}
            </select>
     </div>

     <div class="form-group">
         <label for="{{ form.delivery_type.id_for_label }}">Тип доставки</label>
            <span class="form-error">{{ form.delivery_type.errors }}</span>
            <select name="{{ form.delivery_type.html_name }}" class="custom-input">
                <option value="" selected disabled>Виберіть тип доставки</option>
                {% for value, label in delivery_choices%}
                    <option value="{{ value }}">{{ label }}</option>
                {% endfor %}
            </select>
     </div>
 </div>

myShop/templates/myShop/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

     <div class="section section1">
        <div class="container">
            <div class="row">
             <div class="col-lg-12">
                <h1 class="text-center">
                <!--<div class="section-top">
                    <img src="{% static 'images/banner.jpg' %}" class="img-responsive">
                 </div>-->
                </h1>


                 <h1 class="product_name">
                    <div class="text-center">Товари в магазині</div>
                </h1>
             <div class="filters-container">
                 <div class="filter-sidebar">
                     <h3><b>Фільтрувати:</b></h3>
                     <form method="get">
                        <ul>
                            {{ form.as_p }}
                        </ul>
                    <button type="submit">Фільтр</button>
                </form>
                 </div>
             </div>
             <div class="products-container">
                 {% for product_images in context.products %}
                        {% include 'product_item.html' %}
                {% endfor %}
             </div>

            </div>
        </div>
     </div>

</div>
 {% endblock %}

myShop/templates/myShop/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

            <div class="col-lg-5">
            <h1 class="product_name">{{ product.product_name }}</h1>

            <div class="picture-container">
                {% for image in product.productimage_set.all %}
                    <img src="{{ image.product_image.url }}" width="55%">
                {% endfor %}
            </div>
            </div>

            <div class="col-lg-6">

                <div class="price-container">
                    <h2 class="product_name">Інформація про продукт</h2>
                    <p>
                        Price:{{ product.price }}
                    </p>
                </div>
                <div>
                    <ul class="nav nav-tabs" role="tablist">
                        <li role= "presentation" class="active">
                            <a href="#product_info" aria-controls="home" role="tab" data-toggle="tab">
                                Опис
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#size" aria-controls="profile" role="tab" data-toggle="tab">
                                Розмір
                            </a>
                        </li>
                    </ul>

                      <!-- Tab panes -->
                    <div class="tab-content product-info-tabs">
                        <div role="tabpanel" class="tab-pane active" id="product_info">
                            {{ product.product_info }}
                        </div>
                        <div role="tabpanel" class="tab-pane" id="size">
                            Size of the foot:
                            {{ product.size }}
                        </div>
                    </div>
                </div>
                <br>
                <div>
                    <form id="form_buying_product" class="form-inline" action="{% url 'myShop:basket' %}">{% csrf_token %}
                        <div class="form-group">
                            <input type="number" min="1" class="form-control" name = "num" id="num">
                        </div>
                        <div class="form-group">
                            <button type="submit" id="submit-btn"  class="btn btn-success btn-buy"
                                data-product_id = "{{ product.product_id }}"
                                data-product_name = "{{ product.product_name }}"
                                data-product_price = "{{ product.price }}"
                                    >
                                Обрати кількість
                            </button>
                        </div>
                    </form>
                </div>

                </div>

            </div>

{% endblock %}